"""Thumbnail Forge CLI entry point."""
from __future__ import annotations

import json
import sys
from pathlib import Path

import click
from rich.console import Console
from rich.panel import Panel
from rich.table import Table

from . import __version__, brand, config, hooks as hooks_mod, generator, onboard as onboard_mod


console = Console()


@click.group()
@click.version_option(__version__, prog_name="Thumbnail Forge")
def main() -> None:
    """Thumbnail Forge — the thumb-stopper engine.

    Built by Sebastian Hardy. YouTube: @learnaibeforeitstolate.
    """
    pass


# ─── onboard ───────────────────────────────────────────────────────────────

@main.command()
def onboard() -> None:
    """Run the first-time setup wizard."""
    onboard_mod.run()


# ─── thumb ─────────────────────────────────────────────────────────────────

@main.command()
@click.option("--title", "-t", help="Video title (required if no --transcript)")
@click.option("--transcript", "-T", type=click.Path(exists=True, dir_okay=False),
              help="Path to video transcript or topic description")
@click.option("--count", "-n", default=3, show_default=True,
              help="Number of thumbnail variants to generate")
def thumb(title: str | None, transcript: str | None, count: int) -> None:
    """Generate scored-hook thumbnails for a video."""
    _require_onboarded()
    cfg = config.load()

    if not title and not transcript:
        console.print("[red]Need either --title or --transcript.[/red]")
        sys.exit(1)

    # Assemble the facts-source text
    if transcript:
        text = Path(transcript).read_text(encoding="utf-8")
        if title:
            text = f"Title: {title}\n\n{text}"
    else:
        text = f"Title: {title}"

    effective_title = title or "untitled"
    slug = config.slugify(effective_title)
    vdir = config.video_dir(slug)

    console.print(Panel.fit(
        f"[bold]Video:[/bold] {effective_title}\n"
        f"[bold]Slug:[/bold] {slug}\n"
        f"[bold]Output:[/bold] {vdir / 'out'}",
        border_style="cyan",
    ))

    # ── Step 1: Generate hooks ──
    console.print("\n[bold yellow]1/3[/bold yellow] Generating scored hooks...")
    all_hooks = hooks_mod.generate_hooks(text, count=10)
    if not all_hooks:
        console.print(
            "[red]No hooks could be generated from this transcript. "
            "Try adding more specifics: numbers, named tools, named roles.[/red]"
        )
        sys.exit(1)

    _render_hooks_table(all_hooks)

    picks = hooks_mod.top_n_for_thumbnails(all_hooks, n=count)

    # Save hooks.md
    hooks_path = vdir / "hooks.md"
    hooks_path.write_text(
        f"# Hooks — {effective_title}\n\n"
        f"Generated by Thumbnail Forge v{__version__}.\n\n"
        + hooks_mod.render_hook_table(all_hooks)
        + "\n\n## Top picks for thumbnails\n\n"
        + "\n".join(f"- {h.text} ({h.pattern_name}, {h.score}/20)" for h in picks)
        + "\n",
        encoding="utf-8",
    )
    console.print(f"[green]✓[/green] Saved hooks.md\n")

    # Save context.json
    ctx_path = vdir / "context.json"
    ctx_path.write_text(
        json.dumps({
            "title": effective_title,
            "slug": slug,
            "transcript_path": str(transcript) if transcript else None,
            "hooks": [{"text": h.text, "pattern": h.pattern_id, "score": h.score} for h in all_hooks],
            "picks": [h.text for h in picks],
        }, indent=2),
        encoding="utf-8",
    )

    # ── Step 2: Generate thumbnails ──
    console.print(f"[bold yellow]2/3[/bold yellow] Generating {len(picks)} thumbnails...")
    try:
        results = generator.generate_thumbnail_set(picks, cfg, vdir)
    except Exception as e:
        console.print(f"[red]Generation failed:[/red] {e}")
        sys.exit(1)

    # ── Step 3: Report ──
    console.print(f"\n[bold yellow]3/3[/bold yellow] Done.\n")
    _render_results_table(results)

    console.print(
        f"\n[bold green]✓[/bold green] {len(results)} thumbnails saved to:"
    )
    console.print(f"   [cyan]{vdir / 'out'}[/cyan]\n")
    console.print(f"[dim]{brand.FOOTER_LONG.strip()}[/dim]")


# ─── hooks (standalone) ────────────────────────────────────────────────────

@main.command(name="hooks")
@click.option("--title", "-t", help="Video title")
@click.option("--transcript", "-T", type=click.Path(exists=True, dir_okay=False))
@click.option("--count", "-n", default=10, show_default=True)
def hooks_cmd(title: str | None, transcript: str | None, count: int) -> None:
    """Generate scored hooks without rendering thumbnails."""
    _require_onboarded()
    if transcript:
        text = Path(transcript).read_text(encoding="utf-8")
        if title:
            text = f"Title: {title}\n\n{text}"
    elif title:
        text = f"Title: {title}"
    else:
        console.print("[red]Need --title or --transcript.[/red]")
        sys.exit(1)

    all_hooks = hooks_mod.generate_hooks(text, count=count)
    _render_hooks_table(all_hooks)
    console.print(f"\n[dim]{brand.FOOTER_SHORT}[/dim]")


# ─── config ────────────────────────────────────────────────────────────────

@main.command(name="config")
@click.option("--show", is_flag=True, help="Print current config")
@click.option("--path", is_flag=True, help="Print config file path")
def config_cmd(show: bool, path: bool) -> None:
    """View or edit saved config."""
    if path:
        click.echo(str(config.CONFIG_PATH))
        return
    if show or not any([show, path]):
        cfg = config.load()
        redacted = dict(cfg)
        if redacted.get("gemini_api_key"):
            redacted["gemini_api_key"] = f"...{redacted['gemini_api_key'][-4:]}"
        console.print_json(data=redacted)


# ─── helpers ───────────────────────────────────────────────────────────────

def _require_onboarded() -> None:
    if not config.is_onboarded():
        console.print(
            "[yellow]First-time setup not complete.[/yellow] "
            "Run [cyan]tf onboard[/cyan] first."
        )
        sys.exit(1)


def _render_hooks_table(hooks_list: list) -> None:
    table = Table(title="Scored hooks", show_lines=False)
    table.add_column("#", justify="right", style="dim")
    table.add_column("Hook", style="bold")
    table.add_column("Pattern", style="cyan")
    table.add_column("Spec", justify="right")
    table.add_column("Intrigue", justify="right")
    table.add_column("Score", justify="right", style="bold yellow")
    for i, h in enumerate(hooks_list, 1):
        table.add_row(
            str(i), h.text, h.pattern_name,
            str(h.specificity), str(h.intrigue), str(h.score),
        )
    console.print(table)


def _render_results_table(results: list[dict]) -> None:
    table = Table(title="Generated thumbnails")
    table.add_column("#", justify="right", style="dim")
    table.add_column("File", style="green")
    table.add_column("Hook", style="bold")
    table.add_column("Pattern", style="cyan")
    table.add_column("Score", justify="right", style="yellow")
    for i, r in enumerate(results, 1):
        table.add_row(str(i), r["filename"], r["hook"], r["pattern"], str(r["score"]))
    console.print(table)


if __name__ == "__main__":
    main()
